### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by MigrantBirdd** [uosint-project/uosint#4]
Hey guys;

hope you do all best. first thank you for your great job, then unfortunately i got " ModuleNotFoundError: No module named 'bs4' " after input the last cmnd line: " python uosint.py -u username or --username username ". 
hope you guide to solve this matter as well.

thanks in advance

**Comment by uosint-project** [comment]
pip install beautifulsoup4

" python uosint.py -u username or --username username " for that 

python uosint.py -u YourTargetUsername

**Comment by MigrantBirdd** [comment]
thanks a lot
do you have any recorded clip for better understanding?

**Comment by uosint-project** [comment]
You have given me a good idea, I will add the video to the README. ❤️

Your Video link : [Here](https://drive.google.com/file/d/1ugXPFxalIFqAyZ2aboyYgaconPygjMPo/view?usp=share_link)

**Comment by MigrantBirdd** [comment]
great! sometimes it's very helpful and necessary.

**Comment by MigrantBirdd** [comment]
yes by sure and thank you for your helping.
if i got other issue will contact you again.
good luck

**Comment by uosint-project** [comment]
Yes, if you get any other error, let me know, I will fix it as soon as possible. ❤️
